import type { Metadata } from "next";
import "../styles/globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "LYCA｜林園班聯 22 屆",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body
        className={`antialiased font-custom font-medium min-h-dvh flex flex-col`}
      >
        <header className="fixed top-0 w-full z-10">
          <div className="bg-white px-5 py-3">
            <Link href={"/"}>
              <Image
                src={"/lyca-logo.svg"}
                alt="lyca-logo"
                width={100}
                height={200}
              ></Image>
            </Link>
          </div>
        </header>
        <div className="pt-12">{children}</div>
        <footer className="w-full bg-black p-5 flex flex-col items-center justify-center text-sm gap-2 mt-auto">
          <Image
            className="invert"
            src={"/lyca-logo.svg"}
            alt="lyca-logo"
            width={100}
            height={200}
          ></Image>
          <p className="text-white/50">本網站由班聯會資訊組維護與建置</p>
          <p className="text-white/50">2025 © 林園高中班聯會 版權所有</p>
        </footer>
      </body>
    </html>
  );
}
